/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:75f89c35-d876-4347-b46c-79e8bfc6259c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Wceko996b",
    "aws_user_pools_web_client_id": "15cmv3k98vn3r4rcarekpdsi3p",
    "oauth": {}
};


export default awsmobile;
